# Generated by Django 5.0.6 on 2024-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "d_name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Full Name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=200,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "d_name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Full Name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=200,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "p_d_Details",
                    models.ManyToManyField(
                        to="core.doctor", verbose_name="Choose Doctor"
                    ),
                ),
            ],
        ),
    ]
