# Generated by Django 5.0.6 on 2024-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("taskId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "task",
                    models.CharField(
                        max_length=1500, null=True, verbose_name="Add your task"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
